version: '3'

services: 

  app:
    build: 
      context: ../dockerfile_examples # pasta onde esta o dockerfile
      dockerfile: Dockerfile.Nodejs.dev # nome do dockerfile
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
      - ../Apps_for_docker_files/node:/usr/src/app
    tty: true # para conseguirmos mexer no terminal do container caso precise
    ports: 
      - "3000:3000"
    depends_on: # informa que o container app depende do container db para funcionar
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 # para funcionar de forma correta em qualquer maquina
    container_name: db
    restart: always # se o container cair ele vai subir sozinho
    tty: true # para conseguirmos mexer no terminal do container caso precise
    volumes: 
      - ../Apps_for_docker_files/mysql:/var/lib/mysql # para salvar os dados do banco de dados
    environment: 
      - MYSQL_DATABASE=nodedb # nome do banco de dados
      - MYSQL_ROOT_PASSWORD=root # senha do usuario root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge
